### ISSUE TITLE
"annotations" as defaultdict has no iteritems

### ISSUE THREAD

**Issue by CielAl** [btcrabb/SlideSeg#11]
Python-3.7.0. It appears that changing iteritems to items will resolve the issue.

The given parameters has save_ratio as 'inf', which is a string and not cast to float, and will eventually crash the checksave.

**Comment by CielAl** [comment]
chip_dictionary in run has the same problem.

**Comment by CielAl** [comment]
OK, it appears to be the problem as I am not using python2.7.  
After I fix the issue of defaultdict.iteritem and block the metainfo writing, it can work on Python3.7.

**Comment by btcrabb** [comment]
Hi CielAI,

Yes, SlideSeg was written to run on Python 2.7. Since this is simply a version issue, I'm closing this issue for now.
