### ISSUE TITLE
TypeError: '>' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by A00TB** [btcrabb/SlideSeg#12]
I seem to get the below error, even when wanting all chips from a WSI.

loading test
test loaded successfully
loading annotation data from xml//test.xml
annotations loaded successfully
Scanning slide level 1 of 8
  0%|                                                  | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 27, in main
    slideseg.run(params, filename)
  File "/home/tr00300/Desktop/SlideSeg-master/slideseg.py", line 521, in run
    _mask, _annotations, filename, _suffix, _save_all, _save_ratio)
  File "/home/tr00300/Desktop/SlideSeg-master/slideseg.py", line 452, in getchips
    save = checksave(save_all, pix_list, save_ratio, _save_count_annotated, _save_count_blank)
  File "/home/tr00300/Desktop/SlideSeg-master/slideseg.py", line 339, in checksave
    elif save_count_annotated / float(save_count_blank) > save_ratio:
TypeError: '>' not supported between instances of 'float' and 'str'

The only way I can remove this error is by removing these elif statements from the slideseg.py file. Is there an alternative way to remove this error?

**Comment by btcrabb** [comment]
This sounds like a version issue, are you still using Python 2.7?  Python recently changed how it handles strings and floats, as noted in one of the other issues.
