### ISSUE TITLE
Merging patches into one image

### ISSUE THREAD

**Issue by Suvi-dha** [btcrabb/SlideSeg#9]
Hi, I have really found this software useful for my task. But, I want to merge the patches back into one image to visualize the final detections. Is their a way to do so? Can you help?

**Comment by btcrabb** [comment]
This functionality is currently not a part of SlideSeg. If you had the time to develop such a feature, your contributions would be highly appreciated. Currently, the image patches are saved with their pixel locations embedded in the filename. You could potentially use these to stitch the patches back together. 

Glad you found the software useful!
